version: '3'
services:

  elasticsearch:
    hostname: elasticsearch
    image: elasticsearch:7.6.2
    restart: always
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - ES_HEAP_SIZE=1G
      - TZ=Europe/Istanbul
    volumes:
      - ./elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - "elasticdata:/usr/share/elasticsearch/data"

  logstash:
    hostname: logstash
    image: logstash:7.6.2
    restart: always
    command: -f /etc/logstash/conf.d/

    volumes:

      - ./logstash/logstash.yml:/etc/logstash/conf.d/logstash.yml
    ports:
      - "5044:5044"
    environment:
      - LS_JAVA_OPTS=-Xmx256m -Xms256m
      - TZ=Europe/Istanbul
    depends_on:
      - elasticsearch
  kibana:
    image: kibana:7.6.2
    restart: always
    environment:
      - TZ=Europe/Istanbul
    volumes:

      - ./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    restart: always
    environment:
      RABBITMQ_DEFAULT_VHOST: logsistemi
      RABBITMQ_DEFAULT_USER: serviceadmin
      RABBITMQ_DEFAULT_PASS: 4E7AVjrdOJFAPp
      TZ: Europe/Istanbul
    ports:
      - 5672:5672
      - 15672:15672

volumes:
  elasticdata:
