version: '2'
services:

  elasticsearch:
    hostname: elasticsearch
    image: elasticsearch:7.1.1
    privileged: true
    restart: always
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - ES_HEAP_SIZE=1G
    volumes:
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - "elasticdata:/usr/share/elasticsearch/data"

  logstash:
    hostname: logstash
    image: logstash:7.1.1
    restart: always
    command: -f /etc/logstash/conf.d/
    volumes:
      - ./logstash.yml:/etc/logstash/conf.d/logstash.yml
    ports:
      - "5044:5044"
    environment:
      LS_JAVA_OPTS: "-Xmx512m -Xms512m"
    depends_on:
      - elasticsearch


  kibana:
    image: kibana:7.1.1
    restart: always
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch


volumes:
  elasticdata:
